# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storify_database',
            name='synopsis',
            field=models.CharField(default='Synopsos Unavailable', max_length=150),
        ),
    ]
