# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_storify_database_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storify_database',
            name='synopsis',
            field=models.CharField(default='Synopsis Unavailable', max_length=150),
        ),
    ]
